version: '3'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - 9000:9000
      - 9092:9092
    restart: always

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
    restart: always
# docker run -d -p 8081:8081 --name nexuswitoutvars sonatype/nexus3 => curl http://localhost:8081/nexus/service/local/status

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    restart: always
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    restart: always
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    depends_on:
      - prometheus

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}